### PR TITLE
Add extra field in Resource for middleware

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
Required for pixi-compressed-textures

```
var loader = new PIXI.loaders.Loader();
loader.before( PIXI.compressedTextures.extensionChooser(renderer) );
// use @2x texture if resolution is 2, use dds format if its windows
var textureOptions1 = { metadata: { ext: ["@2x.png", ".dds", "@2x.dds"] } };
// use dds format if its windows but dont care for retina
var textureOptions2 = { metadata: { ext: [".dds"] } };

var atlasOptions = { metadata: { imageMeta: textureOptions.extra } }

var stage = new PIXI.Container();

loader.add('building1', 'img/building1.png', textureOptions1)
    .add('building2', 'img/building2.png', textureOptions2)
    .add('IHateAtlases', 'img/atlas1.json', atlasOptions)
```

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
May be rename it to "params"

**Comment by ivanpopelyshev** [comment]
That's the lib: https://github.com/pixijs/pixi-compressed-textures

**Comment by ivanpopelyshev** [comment]
Ok, I think "metadata" describes it better.

**Comment by englercj** [comment]
Yeah I've thought about what the best way to pass extra parameters to the middleware would be. Let me think on this a bit more before I move forward with anything.

**Comment by ivanpopelyshev** [comment]
If we add one more parameter, it will be added everywhere. Using options is easier. Also, we can stuck there things like inlined atlas for a spritesheet.

**Comment by englercj** [comment]
:+1:

**Pull request merged**
