### PR TITLE
Complete cordova-related tweak to support media files (mp3, m4a, etc.)

### PR DESCRIPTION
**Pull request by cursedcoder**

### CODE REVIEW

**Comment by englercj** [comment]
Can you give some context as to what this fixes, and why it fixes it? Additionally, some tests would be really good.

**Comment by cursedcoder** [comment]
Well,

as for me it fixes loading of media resources such as m4a files,

https://github.com/englercj/resource-loader/pull/13

so this PR is just a complementary to #13 allowing resources with arraybuffer be recognized as valid too

**Comment by cursedcoder** [comment]
Tests - maybe next week.

**Comment by cursedcoder** [comment]
@englercj if I add tests – will you merge?

**Comment by englercj** [comment]
Sure

**Comment by cursedcoder** [comment]
@englercj yo, could you please re-check?

**Pull request merged**
