### PR TITLE
Fix for loading more nested assets than the concurrency limit

### PR DESCRIPTION
**Pull request by tarling**
Attempted fix for https://github.com/englercj/resource-loader/issues/82

- `queue.next()` no longer called on image load in spritesheet middleware, but after image has been requested
- fix for progressChunks adding up to more than 100 because of floating point errors

### CODE REVIEW

**Comment by englercj** [comment]
I appreciate the effort here, but I think I got this one fixed.

I am curious about your "Avoid floating point errors..." commit though. Once complete the loader sets itself to 100 manually to avoid 99.9999, are you getting some other kind of issue?

**Comment by tarling** [comment]
I tweaked the tests to have 3 spritesheets - after doing this, I was ending up with a failed test because the progressChunks were adding up to 100.0000001 or something (see commit f732b59 to see this happening). This was because to get the progressChunk size, 100 was being divided by the number of chunks

With 6 chunks this resulted in something like the following
```
a = 100 / 6
a + a + a + a + a + a //100.00000000000001
```

So in 3dca6ee I kept subtracting the chunk size from 100 and used the remainder for the last chunk

**Comment by englercj** [comment]
So I get that, but the loader sets itself to exactly `100` when loading completes. So if it does go over a bit during some floating point math, it gets overridden by `100` on complete. Were tests failing after you made your change to add a third loading thing?

**Comment by tarling** [comment]
Yes - they were. This can be seen in commit f732b59

```
FAILED TESTS:
  Loader
    events
      with multiple additional subresources
        ✖ should never have an invalid progress value
          Chrome 55.0.2883 (Mac OS X 10.12.0)
        Error: Uncaught AssertionError: expected 100.00000000000001 to be at most 100 (node_modules/chai/chai.js:206)
```

**Comment by englercj** [comment]
Ah, gotcha. I actually feel like that is a case of the test needing an adjustment. I feel like it is OK to have that rounding error, just need to make the test use an epsilon for that variance.

**Pull request closed without merging**
